@base-url = localhost:8080
@realm = ecommerce
@client-id = app-payment-client-2
@client-secret = v1fu68gKbuQccWO5mVSUWv5AwOvu1Ls6
@code-verifier = J0zA1PmWGlQXFyWgX3vA88imBV0iBKxsJZZLbvta39Y
@code-challenge = MC1-tqVFMXNPwT-7tM0OJY1rWm1DRsuoMWIBH39Xu1U

###
# Authetication Code PKCE 1
GET http://{{base-url}}/realms/{{realm}}/protocol/openid-connect/auth
?response_type=code
&client_id={{client-id}}
&client_secret={{client-secret}}
&redirect_uri=http://localhost:8000
&scope=openid app-payment-scope
&state=123456
&code_challenge={{code-challenge}}
&code_challenge_method=S256

###
# Authetication Code PKCE 2
# @prompt code Code authorization
POST http://{{base-url}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&client_id={{client-id}}
&client_secret={{client-secret}}
&code={{code}}
&redirect_uri=http://localhost:8000
&code_verifier={{code-verifier}}

###
POST http://{{base-url}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_secret={{client-secret}}
&client_id={{client-id}}
&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer
&scope=openid app-payment-scope